#ifndef TASK_PRIORITIES_H
#define TASK_PRIORITIES_H

// System priorities (higher number = higher priority)
#define TASK_PRIORITY_MONITOR         2
#define TASK_PRIORITY_DEFAULT         5
#define TASK_PRIORITY_LED             tskIDLE_PRIORITY

// Component-specific priorities
#define TASK_PRIORITY_SENSOR_ALS      TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_SENSOR_PS       TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_TOUCH           TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_MIDI_IN         TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_MIDI_OUT        TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_MIDI_TEMPO      TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_SYNC_BPM        TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_HAPTIC          TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_EXPRESSION      TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_DISPLAY         TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_ANALOG_INPUT    TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_TOUCH2          TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_BUMP            TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_ADC_EXP         TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_ADC_CV          TASK_PRIORITY_DEFAULT
#define TASK_PRIORITY_SPI             TASK_PRIORITY_DEFAULT
#define CONSOLE_TASK_PRIORITY         3  // Lower priority for console

#endif // TASK_PRIORITIES_H
