# increment_build.cmake
# Called at build time to increment build number and generate header

# Read current build number
if(EXISTS "${BUILD_NUMBER_FILE}")
  file(READ "${BUILD_NUMBER_FILE}" BUILD_NUMBER)
  string(STRIP "${BUILD_NUMBER}" BUILD_NUMBER)
  math(EXPR BUILD_NUMBER "${BUILD_NUMBER} + 1")
else()
  set(BUILD_NUMBER 1)
endif()

# Write incremented number back to file (the human-facing build count)
file(WRITE "${BUILD_NUMBER_FILE}" "${BUILD_NUMBER}\n")

# Stamp count+1 into the header. On an incremental build Ninja recompiles
# version.c against the header value from the START of the build, so the binary
# deterministically trails build_number.txt by exactly one through the OTA path
# we actually ship. Writing count+1 cancels that one-build lag, so the number
# the device reports after an OTA update equals build_number.txt.
# Caveat: a from-scratch build (deleted build/) compiles against this build's
# header directly with no lag, so it reads one high for that one build; the next
# incremental build self-corrects.
math(EXPR FW_BUILD_NUMBER "${BUILD_NUMBER} + 1")

# Generate header file
file(WRITE "${BUILD_NUMBER_HEADER}" 
"// Auto-generated by increment_build.cmake - do not edit
#ifndef VERSION_BUILD_H
#define VERSION_BUILD_H
#define FW_BUILD_NUMBER ${FW_BUILD_NUMBER}
#endif
")

message(STATUS "Build number: ${BUILD_NUMBER} (stamped ${FW_BUILD_NUMBER})")

