# increment_build.cmake
# Called at build time to increment build number and generate header

# Read current build number
if(EXISTS "${BUILD_NUMBER_FILE}")
  file(READ "${BUILD_NUMBER_FILE}" BUILD_NUMBER)
  string(STRIP "${BUILD_NUMBER}" BUILD_NUMBER)
  math(EXPR BUILD_NUMBER "${BUILD_NUMBER} + 1")
else()
  set(BUILD_NUMBER 1)
endif()

# Write incremented number back to file
file(WRITE "${BUILD_NUMBER_FILE}" "${BUILD_NUMBER}\n")

# Generate header file
file(WRITE "${BUILD_NUMBER_HEADER}" 
"// Auto-generated by increment_build.cmake - do not edit
#ifndef VERSION_BUILD_H
#define VERSION_BUILD_H
#define FW_BUILD_NUMBER ${BUILD_NUMBER}
#endif
")

message(STATUS "Build number: ${BUILD_NUMBER}")

